### ISSUE TITLE
Allow exporting/storing support

### ISSUE THREAD

**Issue by tglman** [christophertrml/rs-natural#14]
Hi,

Would be cool to be able to serialize/store the trained model somehow, probably would be a good idea provide some API that can access internal structures for store/restore to be able to have independent serialization/storage engines.

Regards

**Comment by tsturzl** [comment]
I've thought similar. If we could provide support for serde, it could offer several different formats. I've done a decent bit of work with serde in other projects, and I'm pretty familiar with this codebase. My only concern is that some things like the Naive Bayes classifier might undergo significant refactor in the future. I'll kick this idea around, and if it seems doable without too much effort I'll send a PR.

**Comment by tsturzl** [comment]
Exporting is supported via optional serde features, you can add this to your Cargo.toml:
```
[dependencies]
natural = { version = "0.4.0", features = ["serde_support"]}
serde = "1.0"
```

This should allow you to serialize the TF-IDF and Bayes Classifier.
