### ISSUE TITLE
Need crates.io access to publish crate

### ISSUE THREAD

**Issue by tsturzl** [christophertrml/rs-natural#19]
Hey @christophertrml,

In order to publish changes I need access on crates.io. When you have time, could you add me? See: https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner

Thanks!

**Comment by tsturzl** [comment]
bump

**Comment by christophertrml** [comment]
Hey Travis, I believe I've invited you to have the crates publish access as of this morning. Also I accidentally removed you as a collaborator and then re-added you, so you'll probably need to re-accept that. Let me know if anything doesn't work right!

**Comment by tsturzl** [comment]
Thanks Chris! Looks like I have access. I also verified that I have travis-ci access already since I'm a collaborator on github. Looks like everything is in order!
